### ISSUE TITLE
`insert` overwrites the entire file if an otp entry already exists

### ISSUE THREAD

**Issue by u91o** [tadfisher/pass-otp#163]
>1
>2
>3
>otpauth://totp/OLD
>a
>b
>c

With the example pass file above, the current behavior of `pass otp insert` overwrites the entire file to be become the following:
>otpauth://totp/NEW

Is this the intended behavior? If so, I think a more explicit warning is warranted considering the risk here. If not, I would like to work on a PR to resolve this.

**Comment by ghost** [comment]
@u91o 
@tadfisher 

Ehm.. why was this closed, it is still an issue. 

I hate this behaviour of pass-otp and in company with https://github.com/tadfisher/pass-otp/issues/169 it makes 
`pass otp add foobar `
totally useless, because it is easier to just run 
`pass edit foobar `
and add the 
`otpauth:// URI `
manually. 

At the moment I use pass-otp only to display the actual otp and nothing more.
