### ISSUE TITLE
user story

### ISSUE THREAD

**Issue by tezeb** [tadfisher/pass-otp#48]
Can you enlighten me what is the use case for this plugin? Don't get me wrong, it's just curiosity as I tried to come up with a compelling user story and couldn't find one.

**Comment by bexelbie** [comment]
I can't speak to the original authors, but this extension allows me to use OTP without having my mobile phone or token near me.  It also provides me with an easy way to "reload" tokens on to my mobile phone client without having to force reset all of my OTP protected accounts.

There is a real (although I judge it to be small) likelihood that the use of this extension makes it easier to break into my accounts.  In order to do that, aiui, an attacker would need to get my pgp private key and my password.  This, I believe, is acceptable as an attacker able to obtain my pgp private key has probably physically stolen my laptop or my backup device.  This means that they could also have stolen any separate token I have.

**Comment by tadfisher** [comment]
The usual OTP scheme assumes your second factor is a smartphone or other
security device, and require your secret to be stored on that device. This
extension allows you to decide what your second factor is, whether that is
a unique `pass` store with a different subkey and passphrase, or a GPG
smartcard that you use with multiple machines, or whatever scheme you
choose.

In my case, I use a Yubikey as my second factor, and my GPG keys are only
accessible from that device. So OTP using a smartphone is rather redundant
for me, and I'd rather store the secrets with everything else the Yubikey
unlocks rather than on the Yubikey itself. This allows me to back up and
sync the *secrets* without compromising the idea of two-factor security.

**Comment by tompre** [comment]
@tadfisher How are you adding the URIs? Most of the time web interfaces only provide the either qrcode or the secret but not the URI in textual form. I find it kind of cumbersome to enter the uri by hand.

**Comment by tadfisher** [comment]
@tompre The README has an example for this using `zbarimg`. It's a little bit more cumbersome than using your phone, but you can use any screenshot tool to capture the QR image and pipe it through `zbarimg` to get the embedded URI.
