### ISSUE TITLE
Possible to have force a subfolder?

### ISSUE THREAD

**Issue by hughdavenport** [tadfisher/pass-otp#6]
I use a subfolder for all my otp secrets, it would be handy to have an env variable for what is the "root" of a pass-otp store, so that I can do `pass-otp insert totp blah` and it saves it as `otp/blah.gpg` instead of `blah.otp`

**Comment by hughdavenport** [comment]
Happy to work on this myself when I get a chance, just storing here so I don't forget :)

**Comment by tadfisher** [comment]
I'm not sure this is in scope, because you could consider this same feature for most pass extensions that store non-password things.

Also, something useful would be to store 2FA tokens alongside existing passwords.

I would probably just add a shell alias or even a local .pass_extension to support this functionality.

**Comment by tadfisher** [comment]
Now that #10 is merged, do you still want to continue storing separate passfiles for OTP keys? Just asking in case there's a use case I missed.

**Comment by hughdavenport** [comment]
Hmm, I think it is still a good idea to have them seperate. My end goal is having seperate git submodule/tree's for otp, so that they can be encrypted for a different gpg key (ie smartcard), so that you would require having said smartcard to get otp out. I think that is a good idea as the whole point of OTP is to have two factor, and if they are both accessible under the same gpg key on the same device then that defeats the purpose.

Thats just my thinking though, your project, just let me know if I can help out anyway :)

**Comment by tadfisher** [comment]
If that's the case, why use the same password store? Something like

```bash
alias pass-otp='PASSWORD_STORE_DIR=~/.otp-store pass'
```

would give you a command that operates on a separate store for OTP purposes.

On the other hand, you can use the same password store with two keys by aliasing:

```bash
alias pass-otp='PASSWORD_STORE_KEY=<some other key id> pass`
```

However, the latter adds a bunch of failure cases when you use the wrong command.

I'm still reluctant to add this sort of feature to an extension, because this is a use case that `pass` should handle itself (and it provides those environment variables to do so).

Regarding the second factor concern: your smartcard is already your second factor, because it has a PIN that you should not write down or tell anyone. The weakest link here is always going to be the password itself; OTP simply makes it much more difficult for an attacker to succeed without possessing your second factor. So using a GPG key stored on your smartcard for both passwords and OTP secrets is fine (and should be done for those sites that do not support OTP authentication).

**Comment by hughdavenport** [comment]
Ah yeh. I've missed latest features of pass, those aliases should work for my case. Currently i have sub folders that encrypt to diff keys, and otp is one of those (most passwords im happy with just the passphrase of gpg key stored on disk, otp i prefer to use the smartcard key with pin)
